/*
 * ContextMenu - jQuery plugin for right-click context menus
 
    更改记录： www.gc-isoft.com
    1. 2009-11-15 richard   a) 增加动态操作菜单定义的方法，包括：getMenuInfo, getMenuItemInfo, addMenuItem, removeMenuItem
                            b) 兼容 popupmenu.js，包括：getPopupMenu, bindContextMenu
 */
(function(f){var a,k,c,h,e,b;var d={menuStyle:{listStyle:"none",padding:"1px",margin:"0px",backgroundColor:"#fff",border:"1px solid #999",width:"150px"},itemStyle:{margin:"0px",color:"#000",display:"block",cursor:"default",padding:"3px",border:"1px solid #fff",backgroundColor:"transparent"},itemHoverStyle:{border:"1px solid #0a246a",backgroundColor:"#b6bdd2"},eventPosX:"pageX",eventPosY:"pageY",shadow:true,onContextMenu:null,onShowMenu:null};f.fn.contextMenu=function(n,m){if(!a){a=f('<div id="jqContextMenu" class="contextMenu"></div>').hide().css({position:"absolute",zIndex:"500"}).appendTo("body").bind("click",function(o){o.stopPropagation()})}if(!k){k=f("<div></div>").css({backgroundColor:"#000",position:"absolute",opacity:0.2,zIndex:499}).appendTo("body").hide()}e=e||[];e.push({id:n,menuStyle:f.extend({},d.menuStyle,m.menuStyle||{}),itemStyle:f.extend({},d.itemStyle,m.itemStyle||{}),itemHoverStyle:f.extend({},d.itemHoverStyle,m.itemHoverStyle||{}),bindings:m.bindings||{},shadow:m.shadow||m.shadow===false?m.shadow:d.shadow,onContextMenu:m.onContextMenu||d.onContextMenu,onShowMenu:m.onShowMenu||d.onShowMenu,eventPosX:m.eventPosX||d.eventPosX,eventPosY:m.eventPosY||d.eventPosY});var l=e.length-1;f(this).bind("contextmenu",function(p){var o=(!!e[l].onContextMenu)?e[l].onContextMenu(p):true;if(o){return i(l,this,p,m)}return false});return this};function i(n,m,o,l){if(m==document){m=o.srcElement||o.target||m;if(!m.disabled&&m.tagName&&",input,textarea,select,image,a,button,".indexOf(","+m.tagName.toLowerCase()+",")>=0){return true}}var p=e[n];h=f("#"+p.id).find("ul:first").clone(true);h.css(p.menuStyle).find("li").css(p.itemStyle).hover(function(){f(this).css(p.itemHoverStyle)},function(){f(this).css(p.itemStyle)}).find("img").css({verticalAlign:"middle",paddingRight:"2px"});a.html(h);if(!!p.onShowMenu&&!p.onShowMenu.call(m,o,a)){return true}a.find("li").each(function(q){var r=this.onclick;if(r){this.onclick=null;if(!this.id||!p.bindings[this.id]){f(this).bind("click",function(s){g();r.call(m,m,b)})}}});f.each(p.bindings,function(r,q){f("#"+r,a).bind("click",function(s){g();q.call(m,m,b)})});a.css({left:o[p.eventPosX],top:o[p.eventPosY]}).show();if(p.shadow){k.css({width:a.width(),height:a.height(),left:o.pageX+2,top:o.pageY+2}).show()}f(document).one("click",g);return false}function g(){a.hide();k.hide()}f.contextMenu={defaults:function(l){f.each(l,function(m,n){if(typeof n=="object"&&d[m]){f.extend(d[m],n)}else{d[m]=n}})},options:function(m){for(var l=0;l<e.length;l++){if(e[l].id==m){return e[l]}}return null},bind:function(o,n,m){for(var l=0;l<e.length;l++){if(e[l].id==o){e[l].bindings[n]=m}}}};

// extends by gc-isoft
var j=window.gcPopupMenu;
window.getPopupMenu=function(){if(!j){window.gcPopupMenu=j=new GCPopupMenu()}return j};GCPopupMenu=function(){this.bindContextMenu=function(m,n,l){f(m).contextMenu(n,l||{})},this.getMenuInfo=function(l){return{item:f("#"+l).find("ul:first").get(0).getElementsByTagName("li")}},this.getMenuItemInfo=function(m,l){return f("#"+l,"#"+m).get(0)},this.addMenuItem=function(r,p,q,n,o){var l=document.createElement("li");l.innerHTML=q;if(p){l.id=p}if(n){if(f.isFunction(n)){f.contextMenu.bind(r,p,n)}else{if(n.indexOf("(")==-1){n+="(this)"}l.setAttribute("onclick",n)}}if(o){var m=f("#"+o,"#"+r);if(m&&m.length>0){m.before(f(l));return l}}f("#"+r).find("ul:first").get(0).appendChild(l);return l},this.removeMenuItem=function(m,l){return f("#"+l,"#"+m).remove().get(0)}}
})(jQuery);$(function(){$("div.contextMenu").hide();

if(!window.showMenu){window.showMenu=function(b,a,d,c){return true}}});
